# Stage 1: Pull Python from the official Python Docker image
FROM python:3.9.20-slim@sha256:5772df931ea2bad11e17170ce221f86c751c91eaa537733f069e20bbbb8e9fa7 AS python-stage

# OPTIONAL: Stage 2: Pull CUDA 11.8
FROM nvidia/cuda:11.8.0-base-ubuntu22.04@sha256:f895871972c1c91eb6a896eee68468f40289395a1e58c492e1be7929d0f8703b AS cuda-stage

# Stage 3: Start from windows-local base image
FROM windowsarena/windows-local@sha256:03a28a46fb8b394c9d150e7c60207f06112bd354408f2ce2545895486256a544

# Define build argument for profiling mode (default is off)
ARG PROFILE_MODE=false

# Install necessary packages and clean up in one layer to reduce image size
RUN apt-get update && apt-get install -y \
    dos2unix \
    libgl1 \
    libevdev-dev \
    python3-dev \
    build-essential \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

# OPTIONAL: Copy CUDA libraries and binaries from CUDA stage
COPY --from=cuda-stage /usr/local/cuda-11.8 /usr/local/cuda-11.8
ENV PATH="/usr/local/cuda-11.8/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda-11.8/lib64"

# Copy Python binaries and libraries from the Python stage
COPY --from=python-stage /usr/local /usr/local

# Ensure scripts are callable
RUN ln -s /usr/local/bin/python /usr/bin/python && \
    ln -s /usr/local/bin/pip /usr/bin/pip

# Copy client application and requirements
COPY src/win-arena-container/client/requirements.txt /client/requirements.txt

# Install Python dependencies from requirements.txt
# Combine all Python package installations into one RUN statement to minimize layering
RUN python -m pip install --no-cache-dir --upgrade pip==24.3.1 && \
    python -m pip install --no-cache-dir -r /client/requirements.txt && \
    python -m pip check && \
    { python --version; python -m pip freeze; } > /client-environment.txt

# Download model weights
RUN mkdir -p /models/groundingDINO/ && \
    wget -q https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth -O /models/groundingDINO/groundingdino_swint_ogc.pth && \
    apt-get update && apt-get install -y git git-lfs && git lfs install && \
    git clone https://huggingface.co/microsoft/OmniParser /models/omni

# Conditionally run the disk usage profiling if PROFILE_MODE is true
RUN if [ "$PROFILE_MODE" = "true" ]; then \
        du -ah / | sort -rh | head -n 50 > /du_output.txt; \
    fi
